// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Credentials
    {
        /// <summary>
        /// Initializes a new instance of the Credentials class.
        /// </summary>
        public Credentials() { }

        /// <summary>
        /// Initializes a new instance of the Credentials class.
        /// </summary>
        public Credentials(string login = default(string), string password = default(string))
        {
            Login = login;
            Password = password;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Login")]
        public string Login { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

    }
}
