// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class KeyRequest
    {
        /// <summary>
        /// Initializes a new instance of the KeyRequest class.
        /// </summary>
        public KeyRequest() { }

        /// <summary>
        /// Initializes a new instance of the KeyRequest class.
        /// </summary>
        public KeyRequest(string username = default(string), string pubKey = default(string))
        {
            Username = username;
            PubKey = pubKey;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PubKey")]
        public string PubKey { get; set; }

    }
}
